### ISSUE TITLE
调用hlsPlaybackUrls时出现异常

### ISSUE THREAD

**Issue by xingfinal** [pili-engineering/pili-sdk-java#57]
com.pili.PiliException: status code 619
        at com.pili.API.saveAs(API.java:374)
        at com.pili.API.hlsPlaybackUrl(API.java:538)
        at com.pili.Stream.hlsPlaybackUrls(Stream.java:165)

麻烦能提供详细些的报错么?

**Comment by longbai** [comment]
https://qiniu.kf5.com/hc/kb/article/190023/
没有 直播数据

**Comment by xingfinal** [comment]
谢谢. 具体出现的情况我们再调试一下, 多谢您的解答.
回头再出现问题时我们会先去知识库中先查询下, 再有问题再咨询您.
万分感谢
